name: terra_rest
description: A lightweight payment management library for terra ecosystem
version: 1.0.4
homepage: "https://github.com/TerraMystics"
repository: "https://github.com/TerraMystics/Terra.Dart.Rest"
documentation: "https://docs.terra.money/"
funding:
  - https://www.patreon.com/dangerchcovich
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  http: ^0.13.5
